name: Deploy docs
on:
  push:
    branches:
      - main
      - alpha

jobs:
  release:
    name: deploy docs
    if: |
      github.repository == 'node-real/uikit' &&
      github.event.commits[0].author.username != 'github-actions[bot]'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Creating .env
        run: |
          cat << EOF > "./website/.env"
            VITE_PARTICLE_APP_APP_ID=$PARTICLE_APP_APP_ID
            VITE_PARTICLE_APP_PROJECT_ID=$PARTICLE_APP_PROJECT_ID
            VITE_PARTICLE_APP_CLIENT_KEY=$PARTICLE_APP_CLIENT_KEY
          EOF
        env:
          PARTICLE_APP_APP_ID: ${{ secrets.PARTICLE_APP_APP_ID }}
          PARTICLE_APP_PROJECT_ID: ${{ secrets.PARTICLE_APP_PROJECT_ID }}
          PARTICLE_APP_CLIENT_KEY: ${{ secrets.PARTICLE_APP_CLIENT_KEY }}

      - name: Build docs
        run: pnpm build:docs

      - name: Redirect
        run: |
          mkdir -p ./website/dist/website/dist
          cat << EOF > "./website/dist/website/dist/index.html"
            <script>window.location.href='https://node-real.github.io/walletkit'</script>
          EOF

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./website/dist
          branch: 'docs'
          clean: true
          force: true
