name: Stable Release
on:
  push:
    branches:
      - main
      - 1.x
      - 0.x

jobs:
  release:
    name: release
    if: github.repository == 'node-real/walletkit'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - name: Build packages
        run: pnpm build

      - name: Exit pre mode
        if: github.event.commits[0].author.username != 'github-actions[bot]'
        run: pnpm ci:exit

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:stable-version
          publish: pnpm ci:publish
          commit: 'chore: update versions'
          title: 'chore: update versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
